# Generated by Django 4.1.2 on 2023-06-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
